server:
  port: 18080

spring:
  application:
    name: ddup-auth-captcha
  cloud:
    nacos:
      discovery:
#        server-addr: http://nacos-web.nacos-demo.com
        server-addr: http://10.211.55.18:30161
        username: nacos
        password: nacos

  redis:
    host: 10.211.55.18
    port: 30027
  thymeleaf:
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    cache: false
    encoding: UTF-8
  mvc:
    static-path-pattern: /static/**


retrofit:
  # 全局转换器工厂
  global-converter-factories:
    - com.github.lianjiatech.retrofit.spring.boot.core.BasicTypeConverterFactory
    - retrofit2.converter.jackson.JacksonConverterFactory
  # 全局调用适配器工厂
  global-call-adapter-factories:
    - com.github.lianjiatech.retrofit.spring.boot.core.BodyCallAdapterFactory
    - com.github.lianjiatech.retrofit.spring.boot.core.ResponseCallAdapterFactory

  # 全局日志打印配置
  global-log:
    # 启用全局日志打印
    enable: true
    # 全局日志打印级别
    log-level: info
    # 全局日志打印策略
    log-strategy: body


  # 全局重试配置
  global-retry:
    # 是否启用全局重试
    enable: true
    # 全局重试间隔时间
    interval-ms: 10
    # 全局最大重试次数
    max-retries: 1
    # 全局重试规则
    retry-rules:
      - response_status_not_2xx
      - occur_io_exception

  # 熔断降级配置
  degrade:
    # 熔断降级类型。默认none，表示不启用熔断降级
    degrade-type: sentinel
    global-sentinel-degrade:
      # 是否开启
      enable: true
      # 各降级策略对应的阈值。平均响应时间(ms)，异常比例(0-1)，异常数量(1-N)
      count: 500

  # 全局连接超时时间
  global-connect-timeout-ms: 10000
  # 全局读取超时时间
  global-read-timeout-ms: 10000
  # 全局写入超时时间
  global-write-timeout-ms: 10000
  # 全局完整调用超时时间
  global-call-timeout-ms: 0
  pool:
    test1:
      max-idle-connections: 3
      keep-alive-second: 100
    test2:
      max-idle-connections: 5
      keep-alive-second: 50
test:
#  baseUrl: https://www.recaptcha.net
  baseUrl: https://www.google.com
  accessKeyId: sdfsdfdsf
  accessKeySecret: sadfsadfsdfsdf
  captchaClientSecret: 6LeEzuofAAAAAH126dJmXhBaOaAAfdfoKeIogUnZ

# 滑块验证码配置， 详细请看 cloud.tianai.captcha.autoconfiguration.ImageCaptchaProperties 类
captcha:
  # 如果项目中使用到了redis，滑块验证码会自动把验证码数据存到redis中， 这里配置redis的key的前缀,默认是captcha:slider
  prefix: captcha
  # 验证码过期时间，默认是2分钟,单位毫秒， 可以根据自身业务进行调整
  expire:
    # 默认缓存时间 2分钟
    default: 10000
    # 针对 点选验证码 过期时间设置为 2分钟， 因为点选验证码验证比较慢，把过期时间调整大一些
    WORD_IMAGE_CLICK: 20000
  # 使用加载系统自带的资源， 默认是true
  init-default-resource: false
  cache:
    # 缓存控制， 默认为false不开启
    enabled: true
    # 验证码会提前缓存一些生成好的验证数据， 默认是20
    cacheSize: 20
    # 缓存拉取失败后等待时间 默认是 5秒钟
    wait-time: 5000
    # 缓存检查间隔 默认是2秒钟
    period: 2000
    secondary:
      # 二次验证， 默认false 不开启
      enabled: false
      # 二次验证过期时间， 默认 2分钟
      expire: 120000
      # 二次验证缓存key前缀，默认是 captcha:secondary
      keyPrefix: "captcha:secondary"
#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#  endpoint:
#    health:
#      show-details: always
